
# Libraries

```{r, message = FALSE}

library(RSQLite)
library(lubridate)
library(dbplyr)
library(dplyr)
library(purrr)
library(ggplot2)
library(xts)
library(ggfortify)
library(ggthemes)
library(maps)
library(mapdata)

```

# Data import

```{r}

# create db connection
conn <- dbConnect(SQLite(), '/data/wildfires/wildfires.sqlite')

# pull the fires table into RAM
fires <- tbl(conn, "Fires") %>%
    select(FIRE_NAME, DISCOVERY_DATE, DISCOVERY_TIME, STAT_CAUSE_DESCR,
           CONT_DATE, CONT_TIME, FIRE_SIZE, LATITUDE, LONGITUDE, STATE) %>%
    collect()

# disconnect from db
dbDisconnect(conn)

```

# Preprocessing

```{r}

julian_to_date <- function(date_num) as.Date(date_num - 2458014.5, origin = '2017-09-18')

# Date Julian days?!?!
fires <- fires %>%
    mutate(DISCOVERY_DATE = julian_to_date(DISCOVERY_DATE),
           CONT_DATE = julian_to_date(CONT_DATE))

# Overwriting the same column is bad practice, as the code block can't be rerun without reloading the data

```

# Getting the number of fires daily

```{r}

fires %>%
    filter(!is.na(DISCOVERY_DATE)) %>%
    group_by(DISCOVERY_DATE) %>%
    summarise(N = n()) %>%
    ggplot(aes(DISCOVERY_DATE, N)) + geom_line() + geom_smooth(method = "lm")

```

```{r}

fires %>%
    filter(!is.na(DISCOVERY_DATE)) %>%
    group_by(DISCOVERY_DATE) %>%
    summarise(N = n()) %>%
    mutate(DOY = as.numeric(strftime(DISCOVERY_DATE, format = "%j"))) %>%
    ggplot(aes(x = DOY, y = N, color = year(DISCOVERY_DATE))) + geom_line()

```

```{r}

fires <- fires %>%
    mutate(DISCOVERY_MTH = floor_date(DISCOVERY_DATE, unit = "month"))

fires %>%
    filter(!is.na(DISCOVERY_MTH)) %>%
    group_by(DISCOVERY_MTH) %>%
    summarise(N = n()) %>%
    ggplot(aes(x = DISCOVERY_MTH, y = N)) + geom_bar(stat = "identity")

```

```{r}

fires %>%
    filter(!is.na(DISCOVERY_DATE)) %>%
    mutate(DISCOVERY_MTH = floor_date(DISCOVERY_DATE, unit = "month")) %>%
    group_by(DISCOVERY_MTH, STAT_CAUSE_DESCR) %>%
    summarise(N = n()) %>%
    ggplot(aes(DISCOVERY_MTH, N)) + geom_line() + geom_smooth() + facet_wrap(~STAT_CAUSE_DESCR, scales = "free")

```

# Burn-time of Fires

Lets look at the burn-time distribution per fire cause

```{r}

fires %>%
    mutate(BURN_DUR = as.numeric(CONT_DATE - DISCOVERY_DATE)) %>%
    ggplot(aes(x = STAT_CAUSE_DESCR, y=BURN_DUR)) + geom_violin() + scale_y_log10()

```